### ISSUE TITLE
Can't find how to change response phrase.

### ISSUE THREAD

**Issue by drift21** [ggeop/Python-voice-assistant#66]
I would like to change response phrases to vocal commands but I can't find how to do this. 
Any advice? 
Thank you.

**Comment by 11Tuvork28** [comment]
You can change the response in the responding skill e.g. in the assistatn_activation.py skill you can  change how it says hello you can do this for all skills. If you have futher question just ask

**Comment by drift21** [comment]
Thank you for your answer. I wanted to reproduce specific audio files as Assistant's response. Is this possible modifying those skills?
Really thank you for your help.

**Comment by 11Tuvork28** [comment]
Yeah sure depends on what you want to change but you can change anything

**Comment by drift21** [comment]
Ok I will try some changes. Thank you so much for your patience!

**Comment by 11Tuvork28** [comment]
No problem, then close
